const actionTypes = {
  GET_TRANSACTIONS: "GET_TRANSACTIONS",
  GET_TRANSACTION_SUMMARY: "GET_TRANSACTION_SUMMARY",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  GET_USER: "GET_USER",
  REGISTER: "REGISTER",
  SET_PIN: "SET_PIN",
  WALLET_TRANSFER: "WALLET_TRANSFER",
};

export default actionTypes;
